sudo: required
services:
  - docker

before_install:
  - docker build -t eferhatg/kubernetion -f ./client/Dockerfile.dev ./client

script:
  - docker run eferhatg/kubernetion npm test -- --coverage

after_success:
  - docker build -t eferhatg/kubernation-client ./client
  - docker build -t eferhatg/kubernation-nginx ./nginx
  - docker build -t eferhatg/kubernation-server ./server
  - docker build -t eferhatg/kubernation-worker ./worker

  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push eferhatg/kubernation-client
  - docker push eferhatg/kubernation-nginx
  - docker push eferhatg/kubernation-server
  - docker push eferhatg/kubernation-worker
